version: '3.7'
services:
  mongodb_container:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: flitters_db
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
